name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: List build output
        run: ls -la dist/
        
      - name: List assets directory
        run: ls -la dist/assets/
        
      - name: List js directory
        run: ls -la dist/assets/js/
        
      - name: List css directory
        run: ls -la dist/assets/css/
        
      - name: Check for main.tsx files
        run: find dist -name "main.tsx" -type f
        
      - name: Check for any .tsx files
        run: find dist -name "*.tsx" -type f
        
      - name: Check for any .ts files
        run: find dist -name "*.ts" -type f
        
      - name: Show dist/index.html content
        run: cat dist/index.html
        
      - name: Show dist/404.html content
        run: cat dist/404.html
        
      - name: Check file permissions
        run: ls -la dist/ && ls -la dist/assets/ && ls -la dist/assets/js/
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
